version: '3.8'

services:
  # Database - PostgreSQL
  #db:
  #  image: postgres:15-alpine
  #  container_name: postgres_db
  #  restart: always
  #  environment:
  #    POSTGRES_USER: ${POSTGRES_USER}
  #    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #    POSTGRES_DB: ${POSTGRES_DB}
  #  ports:
  #    - "5432:5432" # Exposed for local tools
  #  volumes:
  #    - db_data:/var/lib/postgresql/data
  #  networks:
  #    - trascendence_net

  ## Cache - Redis
  #redis:
  #  image: redis:7-alpine
  #  container_name: redis
  #  restart: always
  #  ports:
  #    - "6379:6379"
  #  networks:
  #    - trascendence_net

  # Backend - NestJS
  backend:
    build: ./backend
    container_name: backend 
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend - React
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

#networks:
#  trascendence_net:
#    driver: bridge


